# Generated by Django 3.2.9 on 2022-09-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='introduce',
            field=models.CharField(max_length=90, verbose_name='文章简介'),
        ),
    ]
