# Generated by Django 3.2.9 on 2022-09-17 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_topicviewnum'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='topicviewnum',
            table='topic_topic_view_num',
        ),
        migrations.CreateModel(
            name='TopicThumbsUpNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='点赞量')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.topic')),
            ],
            options={
                'db_table': 'topic_topic_thumbs_up_num',
            },
        ),
    ]
