# Generated by Django 3.2.9 on 2022-09-17 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_auto_20220917_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicthumbsupnum',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='topic.topic'),
        ),
        migrations.AlterField(
            model_name='topicviewnum',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='topic.topic'),
        ),
    ]
