# Generated by Django 3.2.9 on 2022-09-19 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('topic', '0005_auto_20220917_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicThumbsUpUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='topic.topic')),
                ('user', models.ManyToManyField(to='user.UserProfile')),
            ],
            options={
                'db_table': 'topic_topic_thumbs_up_user',
            },
        ),
    ]
