# Generated by Django 3.2.9 on 2022-09-19 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('topic', '0006_topicthumbsupuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicthumbsupuser',
            name='user',
        ),
        migrations.AddField(
            model_name='topicthumbsupuser',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile'),
            preserve_default=False,
        ),
    ]
