# Generated by Django 3.2.9 on 2022-09-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parrent_comment',
            new_name='parrent_id',
        ),
    ]
